"""Change enlace_portafolio to id_portafolio_interno

Revision ID: 090556402208
Revises: 56ac9c136535
Create Date: 2026-04-06 19:59:31.256428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090556402208'
down_revision: Union[str, Sequence[str], None] = '56ac9c136535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscripcion', sa.Column('id_portafolio_interno', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inscripcion', 'portafolio', ['id_portafolio_interno'], ['id_port'], ondelete='SET NULL')
    op.drop_column('inscripcion', 'enlace_portafolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscripcion', sa.Column('enlace_portafolio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inscripcion', type_='foreignkey')
    op.drop_column('inscripcion', 'id_portafolio_interno')
    # ### end Alembic commands ###
