"""Add role and sector

Revision ID: 0e275399726b
Revises: 9c610dcaeb9c
Create Date: 2026-03-26 16:28:50.724737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e275399726b'
down_revision: Union[str, Sequence[str], None] = '9c610dcaeb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='artista'))
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'artistic_area',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'artistic_area',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'sector')
    # ### end Alembic commands ###
