"""Add Chat Mensaje model

Revision ID: 2d6de4d76c77
Revises: 090556402208
Create Date: 2026-04-06 21:07:14.168848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6de4d76c77'
down_revision: Union[str, Sequence[str], None] = '090556402208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensaje',
    sa.Column('id_msg', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_i', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.UUID(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_i'], ['inscripcion.id_i'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remitente_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_msg')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje')
    # ### end Alembic commands ###
