"""Add portafolio and convocatorias extended fields

Revision ID: 56ac9c136535
Revises: f1a2b3c4d5e6
Create Date: 2026-04-06 19:38:45.939940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ac9c136535'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conv', sa.Column('nivel_experiencia', sa.String(length=50), nullable=True))
    op.add_column('conv', sa.Column('tipo_jornada', sa.String(length=50), nullable=True))
    op.add_column('conv', sa.Column('rango_salarial', sa.String(length=100), nullable=True))
    op.add_column('conv', sa.Column('ubicacion', sa.String(length=150), nullable=True))
    op.add_column('det_portafolio', sa.Column('titulo', sa.String(length=150), nullable=True))
    op.add_column('det_portafolio', sa.Column('descripcion', sa.String(length=1000), nullable=True))
    op.add_column('det_portafolio', sa.Column('portada_url', sa.String(length=500), nullable=True))
    op.add_column('det_portafolio', sa.Column('etiquetas', sa.String(length=300), nullable=True))
    op.add_column('inscripcion', sa.Column('estado', sa.String(length=50), server_default='Enviada', nullable=False))
    op.add_column('inscripcion', sa.Column('carta_presentacion', sa.Text(), nullable=True))
    op.add_column('inscripcion', sa.Column('enlace_portafolio', sa.String(length=500), nullable=True))
    op.add_column('inscripcion', sa.Column('cv_url', sa.String(length=500), nullable=True))
    op.add_column('portafolio', sa.Column('descripcion', sa.String(length=1000), nullable=True))
    op.add_column('portafolio', sa.Column('visibilidad', sa.String(length=20), server_default='Publico', nullable=False))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('cover_pic_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_pic_url')
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('portafolio', 'visibilidad')
    op.drop_column('portafolio', 'descripcion')
    op.drop_column('inscripcion', 'cv_url')
    op.drop_column('inscripcion', 'enlace_portafolio')
    op.drop_column('inscripcion', 'carta_presentacion')
    op.drop_column('inscripcion', 'estado')
    op.drop_column('det_portafolio', 'etiquetas')
    op.drop_column('det_portafolio', 'portada_url')
    op.drop_column('det_portafolio', 'descripcion')
    op.drop_column('det_portafolio', 'titulo')
    op.drop_column('conv', 'ubicacion')
    op.drop_column('conv', 'rango_salarial')
    op.drop_column('conv', 'tipo_jornada')
    op.drop_column('conv', 'nivel_experiencia')
    # ### end Alembic commands ###
