"""add habilidades portafolio conv inscripcion tables

Revision ID: 9c610dcaeb9c
Revises: c1d2e3f4b5a6
Create Date: 2026-03-19 15:34:26.195199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c610dcaeb9c'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidades',
    sa.Column('id_hab', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_hab'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('conv',
    sa.Column('id_conv', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('glue', sa.Text(), nullable=True),
    sa.Column('id_usr', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usr'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_conv')
    )
    op.create_table('portafolio',
    sa.Column('id_port', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('id_usr', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usr'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_port')
    )
    op.create_table('rel_usr_hab',
    sa.Column('id_rel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usr', sa.UUID(), nullable=False),
    sa.Column('id_hab', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hab'], ['habilidades.id_hab'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usr'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rel'),
    sa.UniqueConstraint('id_usr', 'id_hab', name='uq_usr_hab')
    )
    op.create_table('det_conv',
    sa.Column('id_dc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('id_usr', sa.UUID(), nullable=False),
    sa.Column('obsr', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_conv'], ['conv.id_conv'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usr'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dc')
    )
    op.create_table('det_portafolio',
    sa.Column('id_det_p', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_port', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('G', 'P')", name='chk_estado_port'),
    sa.ForeignKeyConstraint(['id_port'], ['portafolio.id_port'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_det_p')
    )
    op.create_table('inscripcion',
    sa.Column('id_i', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_conv', sa.Integer(), nullable=False),
    sa.Column('id_usr', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_conv'], ['conv.id_conv'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usr'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_i'),
    sa.UniqueConstraint('id_conv', 'id_usr', name='uq_inscripcion')
    )
    op.alter_column('users', 'artistic_area',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'artistic_area',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('inscripcion')
    op.drop_table('det_portafolio')
    op.drop_table('det_conv')
    op.drop_table('rel_usr_hab')
    op.drop_table('portafolio')
    op.drop_table('conv')
    op.drop_table('habilidades')
    # ### end Alembic commands ###
