"""add onboarding fields to users

Revision ID: 9ec46bc4ce93
Revises: 2f4a6b8c0d1e
Create Date: 2026-08-29 11:32:34.393377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ec46bc4ce93'
down_revision: Union[str, Sequence[str], None] = '2f4a6b8c0d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('artistic_disciplines', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('looking_for_disciplines', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('company_legal_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('company_nit', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('company_size', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'company_size')
    op.drop_column('users', 'company_nit')
    op.drop_column('users', 'company_legal_name')
    op.drop_column('users', 'looking_for_disciplines')
    op.drop_column('users', 'artistic_disciplines')
    op.drop_column('users', 'social_links')
    # ### end Alembic commands ###
