"""add_conversacion_table_refactor_chat

Revision ID: ecc79ba49269
Revises: 2d6de4d76c77
Create Date: 2026-04-08 18:23:28.654119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc79ba49269'
down_revision: Union[str, Sequence[str], None] = '2d6de4d76c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversacion',
    sa.Column('id_conversacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('id_i', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('artista_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_i'], ['inscripcion.id_i'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_conversacion'),
    sa.UniqueConstraint('id_i', name='uq_conversacion_inscripcion')
    )
    op.add_column('mensaje', sa.Column('id_conversacion', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('mensaje_id_i_fkey'), 'mensaje', type_='foreignkey')
    op.create_foreign_key(None, 'mensaje', 'conversacion', ['id_conversacion'], ['id_conversacion'], ondelete='CASCADE')
    op.drop_column('mensaje', 'id_i')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensaje', sa.Column('id_i', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mensaje', type_='foreignkey')
    op.create_foreign_key(op.f('mensaje_id_i_fkey'), 'mensaje', 'inscripcion', ['id_i'], ['id_i'], ondelete='CASCADE')
    op.drop_column('mensaje', 'id_conversacion')
    op.drop_table('conversacion')
    # ### end Alembic commands ###
